from __future__ import annotations

import html
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import pandas as pd

from battery_cycle_analyzer import __version__
from battery_cycle_analyzer.core.comparison import ComparisonResult
from battery_cycle_analyzer.core.data_model import LoadedDataset, SectionStatistics


@dataclass(slots=True)
class AgingReport:
    title: str
    html: str


@dataclass(frozen=True, slots=True)
class AgingReportOptions:
    title: str = "Battery Aging Summary Report"
    notes: str = ""
    plot_image_paths: tuple[Path, ...] = ()


class AgingReportService:
    """Creates lightweight HTML reports without GUI dependencies."""

    def generate_html(
        self,
        datasets: list[LoadedDataset],
        *,
        comparison: ComparisonResult | None = None,
        section_statistics: list[SectionStatistics] | None = None,
        options: AgingReportOptions | None = None,
    ) -> AgingReport:
        options = options or AgingReportOptions()
        parts = [
            "<!doctype html>",
            "<html><head><meta charset='utf-8'>",
            f"<title>{html.escape(options.title)}</title>",
            self._style(),
            "</head><body>",
            f"<h1>{html.escape(options.title)}</h1>",
            f"<p class='muted'>Generated by Battery Cycle Analyzer {html.escape(__version__)}</p>",
        ]
        if options.notes:
            parts.append("<h2>Notes</h2>")
            parts.append(f"<p>{html.escape(options.notes)}</p>")
        parts.append("<h2>Source Data</h2>")
        parts.append(self._dataset_table(datasets))
        if comparison is not None:
            parts.append("<h2>Comparison Summary</h2>")
            parts.append(self._dataframe_table(comparison.summary_frame))
        if section_statistics:
            parts.append("<h2>Selected Section Statistics</h2>")
            parts.append(self._statistics_table(section_statistics))
        if options.plot_image_paths:
            parts.append("<h2>Plot Images</h2>")
            for path in options.plot_image_paths:
                parts.append(
                    f"<figure><img src='{html.escape(str(path))}' alt='Plot image'>"
                    f"<figcaption>{html.escape(path.name)}</figcaption></figure>"
                )
        parts.append("</body></html>")
        return AgingReport(options.title, "\n".join(parts))

    def write_html(self, report: AgingReport, output_path: Path) -> Path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(report.html, encoding="utf-8")
        return output_path

    def _dataset_table(self, datasets: list[LoadedDataset]) -> str:
        rows: list[dict[str, Any]] = []
        for dataset in datasets:
            frame = dataset.frame
            discharge = dataset.discharge_energy_column
            charge = dataset.charge_energy_column
            retention = (
                float(frame["discharge_energy_retention_pct"].dropna().iloc[-1])
                if "discharge_energy_retention_pct" in frame
                and not frame["discharge_energy_retention_pct"].dropna().empty
                else ""
            )
            fade_rate = ""
            if "estimated_cycle_index" in frame and "discharge_energy_retention_pct" in frame:
                valid = frame[["estimated_cycle_index", "discharge_energy_retention_pct"]].dropna()
                if len(valid) >= 2 and valid["estimated_cycle_index"].nunique() >= 2:
                    fade_rate = float(
                        pd.Series(valid["discharge_energy_retention_pct"]).diff().mean()
                    )
            efficiency = (
                float(frame["energy_efficiency"].mean())
                if "energy_efficiency" in frame
                else ""
            )
            rows.append(
                {
                    "source_file": str(dataset.metadata.source_path),
                    "points": len(frame),
                    "discharge_column": discharge or "",
                    "charge_column": charge or "",
                    "units": dataset.metadata.units,
                    "import_rows": dataset.metadata.import_rows,
                    "final_retention_pct": retention,
                    "estimated_fade_rate": fade_rate,
                    "mean_efficiency": efficiency,
                }
            )
        return self._dataframe_table(pd.DataFrame(rows))

    def _statistics_table(self, stats: list[SectionStatistics]) -> str:
        return self._dataframe_table(
            pd.DataFrame(
                [
                    {
                        "curve": item.curve_name,
                        "start": item.start_value,
                        "end": item.end_value,
                        "delta": item.delta,
                        "percent_change": item.percent_change,
                        "min": item.minimum,
                        "max": item.maximum,
                        "mean": item.mean,
                        "median": item.median,
                        "std": item.standard_deviation,
                        "slope": item.slope,
                        "integral": item.integral,
                        "integral_unit": item.integral_unit,
                    }
                    for item in stats
                ]
            )
        )

    def _dataframe_table(self, frame: pd.DataFrame) -> str:
        if frame.empty:
            return "<p>No rows.</p>"
        headers = "".join(f"<th>{html.escape(str(column))}</th>" for column in frame.columns)
        rows = []
        for _, row in frame.iterrows():
            cells = "".join(
                f"<td>{html.escape(str(value))}</td>"
                for value in row.tolist()
            )
            rows.append(f"<tr>{cells}</tr>")
        return f"<table><thead><tr>{headers}</tr></thead><tbody>{''.join(rows)}</tbody></table>"

    def _style(self) -> str:
        return (
            "<style>"
            "body{font-family:Arial,sans-serif;margin:32px;color:#111827;}"
            "table{border-collapse:collapse;width:100%;margin:12px 0 24px;}"
            "th,td{border:1px solid #d1d5db;padding:6px 8px;text-align:left;}"
            "th{background:#f3f4f6;}"
            ".muted{color:#6b7280;}"
            "img{max-width:100%;border:1px solid #d1d5db;}"
            "</style>"
        )
